version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
      gunicorn -w 4 -b 0.0.0.0:80 --log-level debug bot:app"
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: reappraisal_bot
      POSTGRES_USER: nathanpaek
      POSTGRES_PASSWORD: vbriscool
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local